name: "Build and Test"

on:
  workflow_call:
    inputs:
      dotnetVersion:
        type: string
        description: "The path to the project to build and test"
        required: true
        default: 7.0.x
      
jobs:
  build:
    name: Build 
    runs-on: ubuntu-latest
    env:
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 1
      DOTNET_NOLOGO: true
      DOTNET_GENERATE_ASPNET_CERTIFICATE: false
      DOTNET_ADD_GLOBAL_TOOLS_TO_PATH: false
      DOTNET_MULTILEVEL_LOOKUP: 0
      DOTNET_SYSTEM_CONSOLE_ALLOW_ANSI_COLOR_REDIRECTION: true
      TERM: xterm
      PROJECT_PATH: src/mymarketplace.csproj
      AZURE_WEBAPP_NAME: csdkmp
      AZURE_WEBAPP_PACKAGE_PATH: ./publish
      CONFIGURATION: Release

    steps:
    - uses: actions/checkout@v3
      
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: ${{ inputs.dotnetVersion }}

    - name: Restore
      run: dotnet restore ${{ env.PROJECT_PATH }}

    - name: Create build number
      run: |
        now=$(date +'%Y%m%d')
        buildNumber="$now.$GITHUB_RUN_NUMBER"
        echo "BUILD_NUMBER=$buildNumber" >> $GITHUB_ENV"
        echo "$buildNumber"

    - name: Build
      run: dotnet build ${{ env.PROJECT_PATH }} --configuration Release --no-restore -p:BuildNumber=$BUILD_NUMBER -p:SourceRevisionId=$GITHUB_SHA -p:ContinuousIntegrationBuild=true

    - name: Test
      run: dotnet test ${{ env.PROJECT_PATH }} --no-restore --verbosity normal

    - name: Publish
      run: dotnet publish "${{ env.PROJECT_PATH }}" --configuration ${{ env.CONFIGURATION }} --no-build --output "${{ env.AZURE_WEBAPP_PACKAGE_PATH }}"

    - name: Publish Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
