name: "Build and Deploy"

on:
  push:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'
  workflow_dispatch:
    branches:
      - main
    paths-ignore:
      - '**/*.md'
      - '**/*.gitignore'
      - '**/*.gitattributes'

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yaml
    with:
        dotnetVersion: 7.0.x

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    env:
      AZURE_WEBAPP_NAME: ddmp
      AZURE_WEBAPP_PACKAGE_PATH: ./publish

    steps:
    - uses: actions/checkout@v3
  
    - uses: actions/setup-dotnet@v3
  
    - name: Download artifact from build job
      uses: actions/download-artifact@v3
      with:
        name: webapp
        path: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}
      
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Deploy to Azure WebApp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}

    - name: Azure logout
      run: |
        az logout